# Generated by Django 4.0.3 on 2022-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(max_length=50, verbose_name='Symbol')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Price')),
                ('rank', models.IntegerField(blank=True, default=0, verbose_name='Rank')),
                ('image', models.URLField(blank=True, max_length=1000, verbose_name='Image URL')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
